REPOSITORY_CONTEXT: ghcr.io/reshnm
KUSTOMIZATIONS_LOCATION_PREFIX: ${REPOSITORY_CONTEXT}/observability-stack/kustomizations

# cert-manager
CERT_MANAGER_VERSION: "v1.19.3"

# metrics-operator
METRICS_OPERATOR_VERSION: "v0.10.0"

# Kube RBAC Proxy
KUBE_RBAC_PROXY_VERSION: "v0.20.2"

# open telemetry operator and collector
OPEN_TELEMETRY_OPERATOR_CHART_VERSION: "0.106.0"
OPEN_TELEMETRY_OPERATOR_IMAGE_VERSION: "v0.145.0"
OPEN_TELEMETRY_COLLECTOR_IMAGE_VERSION: "v0.146.0"

# prometheus operator
PROMETHEUS_OPERATOR_IMAGE_VERSION: "v0.89.0"
PROMETHEUS_OPERATOR_CONFIG_RELOADER_IMAGE_VERSION: "v0.89.0"

# prometheus
PROMETHEUS_IMAGE_VERSION: "v3.9.1"