REPOSITORY_CONTEXT: ghcr.io/openmcp-project
COMPONENTS_LOCATION: ${REPOSITORY_CONTEXT}/components
KUSTOMIZATIONS_LOCATION_PREFIX: ${REPOSITORY_CONTEXT}/observability-stack/kustomizations

# cert-manager
CERT_MANAGER_VERSION: "v1.21.1"

# metrics-operator
METRICS_OPERATOR_VERSION: "v1.1.0"

# open telemetry operator and collector
OPEN_TELEMETRY_OPERATOR_CHART_VERSION: "0.121.0"
OPEN_TELEMETRY_OPERATOR_IMAGE_VERSION: "v0.156.0"
OPEN_TELEMETRY_COLLECTOR_IMAGE_VERSION: "v0.158.0"

# prometheus operator
PROMETHEUS_OPERATOR_IMAGE_VERSION: "v0.93.1"
PROMETHEUS_OPERATOR_CONFIG_RELOADER_IMAGE_VERSION: "v0.93.1"

# prometheus
PROMETHEUS_IMAGE_VERSION: "v3.13.2"

# prometheus alertmanager
ALERTMANAGER_IMAGE_VERSION: "v0.33.1"

# victoria logs
VICTORIA_LOGS_IMAGE_VERSION: "v1.6.0-victorialogs"


# E2E Test dependencies
# Not used for deployment
# These versions are automatically managed by Renovate
OPENMCP_OPERATOR_VERSION: "v1.3.0"
CLUSTER_PROVIDER_KIND_VERSION: "v0.6.0"
PLATFORM_SERVICE_GATEWAY_VERSION: "v0.1.1"
KRO_VERSION: "0.9.3"
OCM_K8S_TOOLKIT_VERSION: "0.13.0"
