REPOSITORY_CONTEXT: ghcr.io/openmcp-project
COMPONENTS_LOCATION: ${REPOSITORY_CONTEXT}/components
KUSTOMIZATIONS_LOCATION_PREFIX: ${REPOSITORY_CONTEXT}/observability-stack/kustomizations

# cert-manager
CERT_MANAGER_VERSION: "v1.20.0"

# metrics-operator
METRICS_OPERATOR_VERSION: "v0.10.0"

# Kube RBAC Proxy
KUBE_RBAC_PROXY_VERSION: "v0.21.0"

# open telemetry operator and collector
OPEN_TELEMETRY_OPERATOR_CHART_VERSION: "0.106.0"
OPEN_TELEMETRY_OPERATOR_IMAGE_VERSION: "v0.145.0"
OPEN_TELEMETRY_COLLECTOR_IMAGE_VERSION: "v0.146.0"

# prometheus operator
PROMETHEUS_OPERATOR_IMAGE_VERSION: "v0.89.0"
PROMETHEUS_OPERATOR_CONFIG_RELOADER_IMAGE_VERSION: "v0.89.0"

# prometheus
PROMETHEUS_IMAGE_VERSION: "v3.10.0"


# E2E Test dependencies
# Not used for deployment
# These versions are automatically managed by Renovate
OPENMCP_OPERATOR_VERSION: "v0.17.1"
CLUSTER_PROVIDER_KIND_VERSION: "v0.0.15"
PLATFORM_SERVICE_GATEWAY_VERSION: "v0.0.9"
KRO_VERSION: "0.8.5"
OCM_K8S_TOOLKIT_VERSION: "0.0.0-5b3f034"
