---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: alertmanager
  namespace: prometheus-system
spec:
  replicas: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 100m
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: prometheus-system
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 9093
      targetPort: web
      protocol: TCP
  selector:
    app.kubernetes.io/name: alertmanager
