apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-client-ca
spec:
  isCA: true
  commonName: prometheus-client-ca
  secretName: prometheus-client-ca-cert
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: gateway-selfsigned-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: prometheus-client-issuer
spec:
  ca:
    secretName: prometheus-client-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-client-cert
spec:
  secretName: prometheus-client-cert
  commonName: prometheus-client
  usages:
  - client auth
  issuerRef:
    name: prometheus-client-issuer
    kind: Issuer
