apiVersion: metrics.openmcp.cloud/v1alpha1
kind: Metric
metadata:
  name: ocirepository
spec:
  name: co_ocirepository
  description: FluxCD OciRepository
  target:
    kind: OciRepository
    group: source.toolkit.fluxcd.io
    version: v1
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: or_namespace
      fieldPath: "metadata.namespace"
      type: primitive

    - name: or_name
      fieldPath: "metadata.name"
      type: primitive

    - name: or_ready_status
      fieldPath: "status.conditions[?(@.type=='Ready')].status"
      type: primitive
      default: Unknown
