apiVersion: metrics.openmcp.cloud/v1alpha1
kind: Metric
metadata:
  name: kustomization
spec:
  name: ocp_kustomization
  description: FluxCD Kustomizations
  target:
    kind: Kustomization
    group: kustomize.toolkit.fluxcd.io
    version: v1
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: kust_namespace
      fieldPath: "metadata.namespace"
      type: primitive

    - name: kust_name
      fieldPath: "metadata.name"
      type: primitive

    - name: kust_ready_status
      fieldPath: "status.conditions[?(@.type=='Ready')].status"
      type: primitive
      default: Unknown

    - name: kust_healthy_status
      fieldPath: "status.conditions[?(@.type=='Healthy')].status"
      type: primitive
      default: Unknown
