apiVersion: metrics.openmcp.cloud/v1alpha1
kind: Metric
metadata:
  name: helmrelease
spec:
  name: ocp_helmrelease
  description: FluxCD HelmReleases
  target:
    kind: HelmRelease
    group: helm.toolkit.fluxcd.io
    version: v2
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: hr_namespace
      fieldPath: "metadata.namespace"
      type: primitive

    - name: hr_name
      fieldPath: "metadata.name"
      type: primitive

    - name: hr_ready_status
      fieldPath: "status.conditions[?(@.type=='Ready')].status"
      type: primitive
      default: Unknown
