apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-gitrepositories-alerts
  labels:
    prometheus: prometheus
    app: prometheus
spec:
  groups:
    - name: flux.gitrepository
      interval: 30s
      rules:
        - alert: GitRepositoryNotReady
          expr: |
            ocp_gitrepository{gr_ready_status=~"False|Unknown"}
          for: 5m
          labels:
            severity: warning
            component: flux
          annotations:
            summary: "GitRepository {{ $labels.gr_name }} is not ready"
            description: "GitRepository {{ $labels.gr_name }} in namespace {{ $labels.gr_namespace }} on cluster {{ $labels.cluster }} has not been ready for 5 minutes."
