apiVersion: metrics.openmcp.cloud/v1alpha1
kind: DataSink
metadata:
  name: default
spec:
  connection:
    endpoint: "http://default-collector.opentelemetry-collector-system.svc.cluster.local:4318/v1/metrics"
