apiVersion: metrics.open-control-plane.io/v1alpha1
kind: DataSink
metadata:
  name: default
spec:
  connection:
    endpoint: "grpc://default-collector.opentelemetry-collector-system.svc.cluster.local:4317"
