apiVersion: metrics.open-control-plane.io/v1alpha1
kind: Metric
metadata:
  name: e2e-testruns
spec:
  name: opencontrolplane_e2e_testruns
  description: open-control-plane E2E Test Runs
  target:
    kind: E2ETestRun
    group: test-runner.openmcp.cloud
    version: v1alpha1
  interval: "1m"
  dataSinkRef:
    name: default
  valueFrom:
    fieldPath: "metadata.creationTimestamp"
    type: timestamp
  projections:
    - name: obj_name
      fieldPath: "metadata.name"
      type: primitive

    - name: tr_spec_runner_version
      fieldPath: "spec.runner.version"
      type: primitive
      default: Unknown

    - name: tr_tc_create_project_run_status
      fieldPath: "status.testCases[?(@.name=='createProject')].conditions[?(@.type=='RunCompleted')].status"
      type: primitive
      default: Unknown

    - name: tr_tc_create_project_run_reason
      fieldPath: "status.testCases[?(@.name=='createProject')].conditions[?(@.type=='RunCompleted')].reason"
      type: primitive
      default: Unknown

    - name: tr_tc_create_project_cleanup_status
      fieldPath: "status.testCases[?(@.name=='createProject')].conditions[?(@.type=='CleanupCompleted')].status"
      type: primitive
      default: Unknown

    - name: tr_tc_create_project_cleanup_reason
      fieldPath: "status.testCases[?(@.name=='createProject')].conditions[?(@.type=='CleanupCompleted')].reason"
      type: primitive
      default: Unknown

    - name: tr_tc_create_workspace_run_status
      fieldPath: "status.testCases[?(@.name=='createWorkspace')].conditions[?(@.type=='RunCompleted')].status"
      type: primitive
      default: Unknown

    - name: tr_tc_create_workspace_run_reason
      fieldPath: "status.testCases[?(@.name=='createWorkspace')].conditions[?(@.type=='RunCompleted')].reason"
      type: primitive
      default: Unknown

    - name: tr_tc_create_workspace_cleanup_status
      fieldPath: "status.testCases[?(@.name=='createWorkspace')].conditions[?(@.type=='CleanupCompleted')].status"
      type: primitive
      default: Unknown

    - name: tr_tc_create_workspace_cleanup_reason
      fieldPath: "status.testCases[?(@.name=='createWorkspace')].conditions[?(@.type=='CleanupCompleted')].reason"
      type: primitive
      default: Unknown

    - name: tr_tc_create_mcpv2_run_status
      fieldPath: "status.testCases[?(@.name=='createManagedControlPlaneV2')].conditions[?(@.type=='RunCompleted')].status"
      type: primitive
      default: Unknown

    - name: tr_tc_create_mcpv2_run_reason
      fieldPath: "status.testCases[?(@.name=='createManagedControlPlaneV2')].conditions[?(@.type=='RunCompleted')].reason"
      type: primitive
      default: Unknown

    - name: tr_tc_create_mcpv2_cleanup_status
      fieldPath: "status.testCases[?(@.name=='createManagedControlPlaneV2')].conditions[?(@.type=='CleanupCompleted')].status"
      type: primitive
      default: Unknown

    - name: tr_tc_create_mcpv2_cleanup_reason
      fieldPath: "status.testCases[?(@.name=='createManagedControlPlaneV2')].conditions[?(@.type=='CleanupCompleted')].reason"
      type: primitive
      default: Unknown

