apiVersion: metrics.openmcp.cloud/v1alpha1
kind: Metric
metadata:
  name: platformservice
spec:
  name: co_platformservice
  description: openMCP Platform Services
  target:
    kind: PlatformService
    group: openmcp.cloud
    version: v1alpha1
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: ps_name
      fieldPath: "metadata.name"
      type: primitive

    - name: ps_phase
      fieldPath: "status.phase"
      type: primitive
      default: Unknown


