apiVersion: metrics.open-control-plane.io/v1alpha1
kind: FederatedMetric
metadata:
  name: crossplane
spec:
  name: opencontrolplane_crossplane
  description: Crossplane Service Provider Metrics
  target:
    kind: Crossplane
    group: crossplane.services.open-control-plane.io
    version: v1alpha1
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: obj_namespace
      fieldPath: "metadata.namespace"
      type: primitive

    - name: obj_name
      fieldPath: "metadata.name"
      type: primitive

    - name: xp_phase
      fieldPath: "status.phase"
      type: primitive
      default: Unknown

  federateClusterAccessRef:
    name: onboarding-cluster
    namespace: NAMESPACE_PLACEHOLDER
