apiVersion: metrics.openmcp.cloud/v1alpha1
kind: Metric
metadata:
  name: clusterprovider
spec:
  name: opencontrolplane_clusterprovider
  description: open-control-plane Cluster Providers
  target:
    kind: ClusterProvider
    group: openmcp.cloud
    version: v1alpha1
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: obj_name
      fieldPath: "metadata.name"
      type: primitive

    - name: cp_phase
      fieldPath: "status.phase"
      type: primitive
      default: Unknown


