apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: metrics-operator
spec:
  schema:
    apiVersion: v1alpha1
    kind: MetricsOperator
    spec:
      componentRef:
        name: string | default="obs-stack-component"
      imagePullSecretRef:
        name: string | default="imgpull"
        namespace: string | default="obs-stack"
      forProvider:
        namespace: string | default="metrics-operator-system"
        resources:
          requests:
            memory: string | default="64Mi"
            cpu: string | default="10m"
          limits:
            memory: string | default="128Mi"
            cpu: string | default="100m"
    status:
      ready: ${metricsOperatorHelmRelease.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      lastAttemptedRevisionDigest: ${metricsOperatorHelmRelease.status.lastAttemptedRevisionDigest}

  resources:
     # this is the shared image pull secret that will be copied into the metrics-operator namespace
    - id: sharedImagePullSecret
      externalRef:
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${schema.spec.imagePullSecretRef.name}
          namespace: ${schema.spec.imagePullSecretRef.namespace}

    - id: metricsOperatorChart
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: metrics-operator-chart
          namespace: ${schema.metadata.namespace}
        spec:
          componentRef: ${schema.spec.componentRef}
          resource:
            byReference:
              resource:
                name: metrics-operator-chart
              referencePath:
                - name: metrics-operator
          additionalStatusFields:
            registry: resource.access.imageReference.toOCI().registry
            repository: resource.access.imageReference.toOCI().repository
            tag: resource.access.imageReference.toOCI().tag

    - id: metricsOperatorImage
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: metrics-operator-image
          namespace: ${schema.metadata.namespace}
        spec:
          componentRef: ${schema.spec.componentRef}
          resource:
            byReference:
              resource:
                name: metrics-operator-image
              referencePath:
                - name: metrics-operator
          additionalStatusFields:
            registry: resource.access.imageReference.toOCI().registry
            repository: resource.access.imageReference.toOCI().repository
            tag: resource.access.imageReference.toOCI().tag

    - id: metricsOperatorOCIRepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: metrics-operator-ocirepository
          namespace: ${schema.metadata.namespace}
        spec:
          interval: 1m0s
          insecure: true
          layerSelector:
            mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
            operation: copy
          url: oci://${metricsOperatorChart.status.additional.registry}/${metricsOperatorChart.status.additional.repository}
          ref:
            tag: ${metricsOperatorChart.status.additional.tag}
          secretRef:
            name: ${schema.spec.imagePullSecretRef.name}

    - id: metricsOperatorNamespace
      template:
        apiVersion: v1
        kind: Namespace
        metadata:
          name: ${schema.spec.forProvider.namespace}

    - id: metricsOperatorImagePullSecret
      template:
        apiVersion: v1
        kind: Secret
        metadata:
          name: metrics-operator-imgpull
          namespace: ${metricsOperatorNamespace.metadata.name}
        type:  ${sharedImagePullSecret.type}
        data: ${sharedImagePullSecret.data}

    - id: metricsOperatorHelmRelease
      template:
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: metrics-operator-helmrelease
          namespace: ${schema.metadata.namespace}
        spec:
          releaseName: metrics-operator-release
          targetNamespace: ${metricsOperatorNamespace.metadata.name}
          install:
            createNamespace: false
            crds: CreateReplace
          interval: 10m
          timeout: 5m
          chartRef:
            kind: OCIRepository
            name: ${metricsOperatorOCIRepository.metadata.name}
          values:
            imagePullSecrets:
              - name: ${metricsOperatorImagePullSecret.metadata.name}
            image:
              repository: ${metricsOperatorImage.status.additional.registry}/${metricsOperatorImage.status.additional.repository}
              tag: ${metricsOperatorImage.status.additional.tag}
            resources:
              requests:
                memory: ${schema.spec.forProvider.resources.requests.memory}
                cpu: ${schema.spec.forProvider.resources.requests.cpu}
              limits:
                memory: ${schema.spec.forProvider.resources.limits.memory}
                cpu: ${schema.spec.forProvider.resources.limits.cpu}
      readyWhen:
        - ${metricsOperatorHelmRelease.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
