apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: metrics
spec:
  schema:
    apiVersion: v1alpha1
    kind: OpenMCPMetric
    spec:
      componentRef:
        name: string | default="obs-stack-component"
      imagePullSecretRef:
        name: string | default="imgpull"
        namespace: string | default="obs-stack"
      openTelemetryCollector:
        namespace: string | default="open-telemetry-collector-system"
      forProvider:
        namespace: string | default="metrics-operator-system"
    status:
      ready: ${metricsKustomization.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
      lastAttemptedRevisionDigest: ${metricsKustomization.status.lastAttemptedRevision}

  resources:
     # this is the shared image pull secret that will be copied into the metrics namespace
    - id: sharedImagePullSecret
      externalRef:
        apiVersion: v1
        kind: Secret
        metadata:
          name: ${schema.spec.imagePullSecretRef.name}
          namespace: ${schema.spec.imagePullSecretRef.namespace}

    # the prometheus operator kustomization is added here as external because the
    # metrics can't be deployed until the prometheus operator is ready
    - id: prometheusOperatorKustomization
      externalRef:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: prometheus-operator-kustomization
          namespace: ${schema.metadata.namespace}

    - id: metricsKustomizationResource
      template:
        apiVersion: delivery.ocm.software/v1alpha1
        kind: Resource
        metadata:
          name: metrics-kustomization
          namespace: ${schema.metadata.namespace}
        spec:
          componentRef: ${schema.spec.componentRef}
          resource:
            byReference:
              resource:
                name: metrics-kustomization
          additionalStatusFields:
            registry: resource.access.imageReference.toOCI().registry
            repository: resource.access.imageReference.toOCI().repository
            tag: resource.access.imageReference.toOCI().tag
          interval: 1m

    - id: metricsOCIRepository
      template:
        apiVersion: source.toolkit.fluxcd.io/v1
        kind: OCIRepository
        metadata:
          name: metrics-ocirepository
          namespace: ${schema.metadata.namespace}
        spec:
          interval: 1m0s
          insecure: true
          layerSelector:
            mediaType: "application/vnd.cncf.flux.content.v1.tar+gzip"
            operation: copy
          url: oci://${metricsKustomizationResource.status.additional.registry}/${metricsKustomizationResource.status.additional.repository}
          ref:
            tag: ${metricsKustomizationResource.status.additional.tag}
          secretRef:
            name: ${schema.spec.imagePullSecretRef.name}

    - id: metricsKustomization
      template:
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: metrics-kustomization
          namespace: ${schema.metadata.namespace}
        spec:
          interval: 1m
          targetNamespace: ${schema.spec.forProvider.namespace}
          sourceRef:
            kind: OCIRepository
            name: ${metricsOCIRepository.metadata.name}
          path: ""
          prune: true
          timeout: 1m
          patches:
          - target:
              kind: DataSink
              name: default
            patch: |-
              - op: replace
                path: /spec/connection/endpoint
                value: http://default-collector.${schema.spec.openTelemetryCollector.namespace}.svc.cluster.local:4318/v1/metrics
      readyWhen:
        - ${metricsKustomization.status.conditions.exists(c, c.type == "Ready" && c.status == "True")}
