apiVersion: metrics.openmcp.cloud/v1alpha1
kind: FederatedMetric
metadata:
  name: controlplane
spec:
  name: ocp_controlplane
  description: Control Plane Metrics
  target:
    kind: ControlPlane
    group: core.open-control-plane.io
    version: v2alpha1
  interval: "1m"
  dataSinkRef:
    name: default
  projections:
    - name: cp_namespace
      fieldPath: "metadata.namespace"
      type: primitive

    - name: cp_name
      fieldPath: "metadata.name"
      type: primitive

    - name: cp_phase
      fieldPath: "status.phase"
      type: primitive
      default: Unknown

  federateClusterAccessRef:
    name: onboarding-cluster
    namespace: NAMESPACE_PLACEHOLDER