apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: open-control-plane-controlplane-alerts
  labels:
    prometheus: prometheus
    app: prometheus
spec:
  groups:
    - name: open-control-plane.controlplane
      interval: 30s
      rules:
        - alert: ControlPlanePhaseNotReady
          expr: |
            opencontrolplane_controlplane{cp_phase!="Ready"}
          for: 30m
          labels:
            severity: warning
            component: controlplane
            inhibit_alert: "true"
          annotations:
            summary: "ControlPlane {{ $labels.obj_name }} in namespace {{ $labels.obj_namespace }} is not in phase Ready"
            description: "ControlPlane {{ $labels.obj_name }} in namespace {{ $labels.obj_namespace }} on cluster {{ $labels.cluster }} is not in phase Ready."