apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: open-control-plane-clusterrequest-alerts
  labels:
    prometheus: prometheus
    app: prometheus
spec:
  groups:
    - name: open-control-plane.clusterrequest
      interval: 30s
      rules:
        - alert: ClusterRequestPhaseNotGranted
          expr: |
            opencontrolplane_clusterrequests{cr_phase!="Granted"}
          for: 40m
          labels:
            severity: warning
            component: deployment
          annotations:
            summary: "ClusterRequest {{ $labels.cr_name }} is not in phase Granted"
            description: "ClusterRequest {{ $labels.cr_name }} on cluster {{ $labels.cluster }} is not in phase Granted."
