apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: open-control-plane-accessrequest-alerts
  labels:
    prometheus: prometheus
    app: prometheus
spec:
  groups:
    - name: open-control-plane.accessrequest
      interval: 30s
      rules:
        - alert: AccessRequestPhaseNotGranted
          expr: |
            ocp_accessrequests{ar_phase!="Granted"}
          for: 5m
          labels:
            severity: warning
            component: deployment
          annotations:
            summary: "AccessRequest {{ $labels.ar_name }} is not in phase Granted"
            description: "AccessRequest {{ $labels.ar_name }} on cluster {{ $labels.cluster }} is not in phase Granted."
