apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: open-control-plane-cluster-alerts
  labels:
    prometheus: prometheus
    app: prometheus
spec:
  groups:
    - name: open-control-plane.cluster
      interval: 30s
      rules:
        - alert: ClusterPhaseNotReady
          expr: |
            opencontrolplane_clusters{cl_phase!="Ready"}
          for: 40m
          labels:
            severity: warning
            component: deployment
          annotations:
            summary: "Cluster {{ $labels.cl_name }} is not in phase Ready"
            description: "Cluster {{ $labels.cl_name }} on cluster {{ $labels.cluster }} is not in phase Ready."
