apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: open-control-plane-gateway-alerts
  labels:
    prometheus: prometheus
    app: prometheus
spec:
  groups:
    - name: open-control-plane.gateway
      interval: 30s
      rules:
        - alert: GatewayNotProgrammed
          expr: |
            opencontrolplane_gateway{gw_programmed_status!="True"}
          for: 5m
          labels:
            severity: warning
            component: deployment
          annotations:
            summary: "Gateway {{ $labels.obj_name }} on cluster {{ $labels.cluster }} is not in Programmed"
            description: "Gateway {{ $labels.obj_name }} in namespace {{ $labels.obj_namespace }} on cluster {{ $labels.cluster }} is not in Programmed."

        - alert: GatewayNotAccepted
          expr: |
            opencontrolplane_gateway{gw_accepted_status!="True"}
          for: 5m
          labels:
            severity: warning
            component: deployment
          annotations:
            summary: "Gateway {{ $labels.obj_name }} on cluster {{ $labels.cluster }} is not in Accepted"
            description: "Gateway {{ $labels.obj_name }} in namespace {{ $labels.obj_namespace }} on cluster {{ $labels.cluster }} is not in Accepted."
