apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - victoria-logs.yaml
  - gateway.yaml
  - gateway-issuer.yaml
  - gateway-certificate.yaml
  - client-certificates.yaml
  - httproute.yaml
