apiVersion: clusters.openmcp.cloud/v1alpha1
kind: AccessRequest
metadata:
  name: onboarding-cluster
spec:
  clusterRef:
    name: onboarding
    namespace: openmcp-system
  token:
    permissions:
    - rules:
      - apiGroups:
        - '*'
        resources:
        - '*'
        verbs:
        - get
        - list
        - watch
---
apiVersion: metrics.openmcp.cloud/v1alpha1
kind: FederatedClusterAccess
metadata:
  name: onboarding-cluster
spec:
  fieldSelector: "metadata.name=onboarding-cluster,metadata.namespace=NAMESPACE_PLACEHOLDER"
  target:
    kind: AccessRequest
    group: clusters.openmcp.cloud
    version: v1alpha1
  secretRefPath: status.secretRef
